export const data = [
  {
    name: "volvo",
    model: "XC90 Recharge",
    image: "cars/Volvo.webp",
    category: "Luxury SUV",
    loanPrice: "₦185,000 / day",
    duration: "1 Day",
    rating: 4.8,
  },
  {
    name: "Cadillac",
    model: "Escalade IQ",
    image: "cars/Cadillac.webp",
    category: "Executive SUV",
    loanPrice: "₦320,000 / day",
    duration: "1 Day",
    rating: 4.9,
  },
  {
    name: "lexus",
    model: "RX 350h",
    image: "cars/Lexus.webp",
    category: "Premium Crossover",
    loanPrice: "₦175,000 / day",
    duration: "1 Day",
    rating: 4.7,
  },
  {
    name: "Lincoln",
    model: "Navigator L",
    image: "cars/Lincoln_Navigator.webp",
    category: "Luxury SUV",
    loanPrice: "₦280,000 / day",
    duration: "1 Day",
    rating: 4.9,
  },
  {
    name: "Acura",
    model: "MDX Type S",
    image: "cars/Acura.webp",
    category: "Sport SUV",
    loanPrice: "₦150,000 / day",
    duration: "1 Day",
    rating: 4.6,
  },
  {
    name: "GMC",
    model: "Sierra Denali",
    image: "cars/GMC_Sierra.webp",
    category: "Truck",
    loanPrice: "₦200,000 / day",
    duration: "1 Day",
    rating: 4.8,
  },
  {
    name: "Genesis",
    model: "GV80 Coupe",
    image: "cars/Genesis.webp",
    category: "Luxury Coupe",
    loanPrice: "₦180,000 / day",
    duration: "1 Day",
    rating: 4.9,
  },
  {
    name: "Jeep",
    model: "Grand Wagoneer",
    image: "cars/Jeep_Grand_Wagoneer.webp",
    category: "Adventure SUV",
    loanPrice: "₦220,000 / day",
    duration: "1 Day",
    rating: 4.7,
  },
];

export const TopRated = [
  {
    name: "Lincoln",
    model: "Navigator",
    image: "cars/Lincoln_Navigator.webp",
    category: "Luxury SUV",
    loanPrice: "₦250,000 / day",
    duration: "1 Day",
    rating: 4.9,
  },
  {
    name: "Genesis",
    model: "GV80",
    image: "cars/Genesis.webp",
    category: "Premium Crossover",
    loanPrice: "₦165,000 / day",
    duration: "1 Day",
    rating: 4.8,
  },
  {
    name: "Cadillac",
    model: "Escalade",
    image: "cars/Cadillac.webp",
    category: "Executive SUV",
    loanPrice: "₦300,000 / day",
    duration: "1 Day",
    rating: 4.9,
  },
  {
    name: "Jeep",
    model: "Grand Wagoneer",
    image: "cars/Jeep_Grand_Wagoneer.webp",
    category: "Adventure SUV",
    loanPrice: "₦195,000 / day",
    duration: "1 Day",
    rating: 4.7,
  },
];

export const BudgetFriendly = [
  {
    name: "Acura",
    model: "Integra",
    image: "cars/Acura.webp",
    category: "Compact Sport",
    loanPrice: "₦35,000 / day",
    duration: "1 Day",
    rating: 4.5,
  },
  {
    name: "Lexus",
    model: "UX 250h",
    image: "cars/Lexus.webp",
    category: "Compact SUV",
    loanPrice: "₦40,000 / day",
    duration: "1 Day",
    rating: 4.6,
  },
  {
    name: "Cadillac",
    model: "CT4",
    image: "cars/Cadillac.webp",
    category: "Luxury Sedan",
    loanPrice: "₦45,000 / day",
    duration: "1 Day",
    rating: 4.7,
  },
  {
    name: "Genesis",
    model: "G70",
    image: "cars/Genesis.webp",
    category: "Sport Sedan",
    loanPrice: "₦38,000 / day",
    duration: "1 Day",
    rating: 4.8,
  },
];

export const dailyRentalData = [
  { day: "1", rentals: 12 },
  { day: "2", rentals: 15 },
  { day: "3", rentals: 10 },
  { day: "4", rentals: 18 },
  { day: "5", rentals: 20 },
  { day: "6", rentals: 22 },
  { day: "7", rentals: 25 },
  { day: "8", rentals: 19 },
  { day: "9", rentals: 17 },
  { day: "10", rentals: 23 },
  { day: "11", rentals: 28 },
  { day: "12", rentals: 30 },
  { day: "13", rentals: 27 },
  { day: "14", rentals: 26 },
  { day: "15", rentals: 29 },
  { day: "16", rentals: 31 },
  { day: "17", rentals: 34 },
  { day: "18", rentals: 32 },
  { day: "19", rentals: 28 },
  { day: "20", rentals: 35 },
  { day: "21", rentals: 38 },
  { day: "22", rentals: 40 },
  { day: "23", rentals: 37 },
  { day: "24", rentals: 36 },
  { day: "25", rentals: 42 },
  { day: "26", rentals: 45 },
  { day: "27", rentals: 43 },
  { day: "28", rentals: 46 },
  { day: "29", rentals: 48 },
  { day: "30", rentals: 50 },
];

export const topCarsData = [
  { name: "Toyota Corolla", value: 120 },
  { name: "Honda Civic", value: 95 },
  { name: "Hyundai Elantra", value: 80 },
  { name: "Kia Rio", value: 65 },
  { name: "Toyota Camry", value: 50 },
];

export const COLORS = [
  "#2563eb", // blue
  "#16a34a", // green
  "#f59e0b", // amber
  "#dc2626", // red
  "#7c3aed", // purple
];

export const sparkData = [
  { value: 10 },
  { value: 14 },
  { value: 12 },
  { value: 18 },
  { value: 16 },
];

export const COLORSTATS = {
  blue: {
    bg: "bg-blue-50 dark:bg-blue-900/30",
    iconBg: "bg-blue-100 dark:bg-blue-800",
    iconText: "text-blue-600 dark:text-blue-300",
    spark: "#2563eb",
  },
  green: {
    bg: "bg-green-50 dark:bg-green-900/30",
    iconBg: "bg-green-100 dark:bg-green-800",
    iconText: "text-green-600 dark:text-green-300",
    spark: "#16a34a",
  },
  purple: {
    bg: "bg-purple-50 dark:bg-purple-900/30",
    iconBg: "bg-purple-100 dark:bg-purple-800",
    iconText: "text-purple-600 dark:text-purple-300",
    spark: "#7c3aed",
  },
  orange: {
    bg: "bg-orange-50 dark:bg-orange-900/30",
    iconBg: "bg-orange-100 dark:bg-orange-800",
    iconText: "text-orange-600 dark:text-orange-300",
    spark: "#ea580c",
  },
};

export const recentOrders = [
  {
    id: "ORD-001",
    customer: "John Doe",
    car: "Toyota Corolla",
    date: "2025-12-20",
    status: "Completed",
  },
  {
    id: "ORD-002",
    customer: "Jane Smith",
    car: "Honda Civic",
    date: "2025-12-21",
    status: "Pending",
  },
  {
    id: "ORD-003",
    customer: "Mike Johnson",
    car: "Hyundai Elantra",
    date: "2025-12-21",
    status: "Cancelled",
  },
  {
    id: "ORD-004",
    customer: "Sarah Connor",
    car: "Kia Rio",
    date: "2025-12-22",
    status: "Completed",
  },
];

export const recentActivity = [
  {
    user: "John Doe",
    action: "Booked Toyota Corolla",
    time: "2 hours ago",
    icon: "Car",
  },
  {
    user: "Jane Smith",
    action: "Payment Pending for Honda Civic",
    time: "4 hours ago",
    icon: "CreditCard",
  },
  {
    user: "Mike Johnson",
    action: "Cancelled Hyundai Elantra",
    time: "6 hours ago",
    icon: "XCircle",
  },
  {
    user: "Sarah Connor",
    action: "Returned Kia Rio",
    time: "1 day ago",
    icon: "CheckCircle",
  },
];

export const carsDashData = [
  {
    id: 1,
    name: "Toyota Corolla",
    model: "LAG-234-AA",
    pricePerDay: 15000,
    status: "available", // available | rented | maintenance
    published: true,
    image: "/cars/corolla.jpg",
  },
  {
    id: 2,
    name: "Honda Civic",
    model: "ABJ-983-KD",
    pricePerDay: 18000,
    status: "rented",
    published: false,
    image: "/cars/civic.jpg",
  },
  {
    id: 3,
    name: "Suzuki Swift",
    model: "LAG-201-AB",
    pricePerDay: 12000,
    status: "available",
    published: true,
    image: "/cars/swift.jpg",
  },
  {
    id: 4,
    name: "Toyota Yaris",
    model: "LAG-202-BC",
    pricePerDay: 13000,
    status: "rented",
    published: false,
    image: "/cars/yaris.jpg",
  },
  {
    id: 5,
    name: "Ford Escape",
    model: "LAG-203-CD",
    pricePerDay: 21000,
    status: "maintenance",
    published: false,
    image: "/cars/escape.jpg",
  },
  {
    id: 6,
    name: "Nissan Altima",
    model: "LAG-601-XY",
    pricePerDay: 17000,
    status: "available",
    published: true,
    image: "/cars/altima.jpg",
  },
  {
    id: 7,
    name: "Ford Focus",
    model: "LAG-602-ZA",
    pricePerDay: 14000,
    status: "rented",
    published: false,
    image: "/cars/focus.jpg",
  },
  {
    id: 8,
    name: "BMW 3 Series",
    model: "LAG-603-BB",
    pricePerDay: 45000,
    status: "available",
    published: true,
    image: "/cars/bmw3.jpg",
  },
  {
    id: 9,
    name: "Mercedes C-Class",
    model: "LAG-604-CC",
    pricePerDay: 52000,
    status: "maintenance",
    published: false,
    image: "/cars/mercedes_c.jpg",
  },
  {
    id: 10,
    name: "Audi A4",
    model: "LAG-605-DD",
    pricePerDay: 48000,
    status: "available",
    published: true,
    image: "/cars/audi_a4.jpg",
  },
  {
    id: 11,
    name: "Subaru Outback",
    model: "LAG-606-EE",
    pricePerDay: 22000,
    status: "available",
    published: true,
    image: "/cars/outback.jpg",
  },
  {
    id: 12,
    name: "Kia Sportage",
    model: "LAG-607-FF",
    pricePerDay: 20000,
    status: "rented",
    published: false,
    image: "/cars/sportage.jpg",
  },
  {
    id: 13,
    name: "Hyundai Santa Fe",
    model: "LAG-608-GG",
    pricePerDay: 24000,
    status: "available",
    published: true,
    image: "/cars/santafe.jpg",
  },
  {
    id: 14,
    name: "Volkswagen Passat",
    model: "LAG-609-HH",
    pricePerDay: 21000,
    status: "maintenance",
    published: false,
    image: "/cars/passat.jpg",
  },
  {
    id: 15,
    name: "Chevrolet Malibu",
    model: "LAG-610-II",
    pricePerDay: 19000,
    status: "rented",
    published: true,
    image: "/cars/malibu.jpg",
  },
  {
    id: 16,
    name: "Mazda 6",
    model: "LAG-611-JJ",
    pricePerDay: 19500,
    status: "available",
    published: false,
    image: "/cars/mazda6.jpg",
  },
  {
    id: 17,
    name: "Lexus ES",
    model: "LAG-612-KK",
    pricePerDay: 55000,
    status: "available",
    published: true,
    image: "/cars/lexus_es.jpg",
  },
  {
    id: 18,
    name: "GMC Yukon",
    model: "LAG-613-LL",
    pricePerDay: 60000,
    status: "rented",
    published: false,
    image: "/cars/yukon.jpg",
  },
  {
    id: 19,
    name: "Infiniti Q50",
    model: "LAG-614-MM",
    pricePerDay: 47000,
    status: "available",
    published: true,
    image: "/cars/q50.jpg",
  },
  {
    id: 20,
    name: "Mitsubishi Outlander",
    model: "LAG-615-NN",
    pricePerDay: 23000,
    status: "maintenance",
    published: false,
    image: "/cars/outlander.jpg",
  },
  {
    id: 21,
    name: "Peugeot 3008",
    model: "LAG-616-OO",
    pricePerDay: 18000,
    status: "available",
    published: true,
    image: "/cars/peugeot3008.jpg",
  },
  {
    id: 22,
    name: "Renault Koleos",
    model: "LAG-617-PP",
    pricePerDay: 17500,
    status: "available",
    published: false,
    image: "/cars/koleos.jpg",
  },
  {
    id: 23,
    name: "Skoda Octavia",
    model: "LAG-618-QQ",
    pricePerDay: 16000,
    status: "rented",
    published: true,
    image: "/cars/octavia.jpg",
  },
  {
    id: 24,
    name: "Mini Cooper",
    model: "LAG-619-RR",
    pricePerDay: 25000,
    status: "available",
    published: true,
    image: "/cars/mini.jpg",
  },
  {
    id: 25,
    name: "Toyota Camry",
    model: "LAG-620-SS",
    pricePerDay: 26000,
    status: "available",
    published: true,
    image: "/cars/camry.jpg",
  },
];

export const recentPayments = [
  {
    id: "TRX-9871",
    customer: "John Doe",
    amount: "₦15,000",
    date: "2025-12-20",
    status: "Success",
    method: "Credit Card",
    car: {
      name: "Toyota Corolla",
      image: "/cars/corolla.jpg",
      plate: "LAG-234-AA",
    },
  },
  {
    id: "TRX-9872",
    customer: "Jane Smith",
    amount: "₦18,000",
    date: "2025-12-21",
    status: "Pending",
    method: "Bank Transfer",
    car: {
      name: "Honda Civic",
      image: "/cars/civic.jpg",
      plate: "ABJ-983-KD",
    },
  },
  {
    id: "TRX-9873",
    customer: "Mike Johnson",
    amount: "₦12,000",
    date: "2025-12-21",
    status: "Failed",
    method: "Credit Card",
    car: {
      name: "Hyundai Elantra",
      image: "/cars/elantra.jpg", // Assuming image exists or placeholder
      plate: "LAG-999-XX",
    },
  },
  {
    id: "TRX-9874",
    customer: "Sarah Connor",
    amount: "₦13,000",
    date: "2025-12-22",
    status: "Success",
    method: "Paypal",
    car: {
      name: "Kia Rio",
      image: "/cars/rio.jpg", // Assuming image exists or placeholder
      plate: "LAG-777-YY",
    },
  },
  {
    id: "TRX-9875",
    customer: "Kyle Reese",
    amount: "₦21,000",
    date: "2025-12-23",
    status: "Success",
    method: "Crypto",
    car: {
      name: "Toyota Camry",
      image: "/cars/camry.jpg",
      plate: "LAG-620-SS",
    },
  },
];

export const customersList = [
  {
    id: "CUST-001",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+234 801 234 5678",
    totalSpent: "₦450,000",
    rentalsCount: 12,
    status: "Active",
    joinDate: "2024-01-15",
    image: "/avatars/avatar-1.jpg",
  },
  {
    id: "CUST-002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+234 802 345 6789",
    totalSpent: "₦1,200,000",
    rentalsCount: 28,
    status: "Active",
    joinDate: "2023-11-20",
    image: "/avatars/avatar-2.jpg",
  },
  {
    id: "CUST-003",
    name: "Mike Johnson",
    email: "mike.j@example.com",
    phone: "+234 803 456 7890",
    totalSpent: "₦85,000",
    rentalsCount: 3,
    status: "Inactive",
    joinDate: "2024-03-10",
    image: "/avatars/avatar-3.jpg",
  },
  {
    id: "CUST-004",
    name: "Sarah Connor",
    email: "sarah.c@example.com",
    phone: "+234 804 567 8901",
    totalSpent: "₦2,500,000",
    rentalsCount: 45,
    status: "Active",
    joinDate: "2023-05-12",
    image: "/avatars/avatar-4.jpg",
  },
  {
    id: "CUST-005",
    name: "Kyle Reese",
    email: "kyle.reese@example.com",
    phone: "+234 805 678 9012",
    totalSpent: "₦320,000",
    rentalsCount: 8,
    status: "Active",
    joinDate: "2024-02-28",
    image: "/avatars/avatar-5.jpg",
  },
  {
    id: "CUST-006",
    name: "Ellen Ripley",
    email: "ellen.r@example.com",
    phone: "+234 806 789 0123",
    totalSpent: "₦0",
    rentalsCount: 0,
    status: "New",
    joinDate: "2025-12-24",
    image: "/avatars/avatar-6.jpg",
  },
  {
    id: "CUST-007",
    name: "Bruce Wayne",
    email: "bruce@wayne.com",
    phone: "+234 807 890 1234",
    totalSpent: "₦5,000,000",
    rentalsCount: 15,
    status: "Active",
    joinDate: "2023-08-15",
    image: "/avatars/avatar-7.jpg",
  },
];

export const allOrders = [
  {
    id: "ORD-7829",
    customer: {
      name: "John Doe",
      email: "john.doe@example.com",
      image: "/avatars/avatar-1.jpg",
    },
    car: {
      name: "Toyota Corolla",
      image: "/cars/corolla.jpg",
      plate: "LAG-234-AA",
    },
    startDate: "2025-12-20",
    endDate: "2025-12-25",
    amount: "₦75,000",
    status: "Completed",
  },
  {
    id: "ORD-7830",
    customer: {
      name: "Jane Smith",
      email: "jane.smith@example.com",
      image: "/avatars/avatar-2.jpg",
    },
    car: { name: "Honda Civic", image: "/cars/civic.jpg", plate: "ABJ-983-KD" },
    startDate: "2025-12-21",
    endDate: "2025-12-23",
    amount: "₦36,000",
    status: "Pending",
  },
  {
    id: "ORD-7831",
    customer: {
      name: "Mike Johnson",
      email: "mike.j@example.com",
      image: "/avatars/avatar-3.jpg",
    },
    car: {
      name: "Hyundai Elantra",
      image: "/cars/elantra.jpg",
      plate: "LAG-999-XX",
    },
    startDate: "2025-12-21",
    endDate: "2025-12-21",
    amount: "₦12,000",
    status: "Cancelled",
  },
  {
    id: "ORD-7832",
    customer: {
      name: "Sarah Connor",
      email: "sarah.c@example.com",
      image: "/avatars/avatar-4.jpg",
    },
    car: { name: "Kia Rio", image: "/cars/rio.jpg", plate: "LAG-777-YY" },
    startDate: "2025-12-22",
    endDate: "2025-12-28",
    amount: "₦78,000",
    status: "Ongoing",
  },
  {
    id: "ORD-7833",
    customer: {
      name: "Kyle Reese",
      email: "kyle.reese@example.com",
      image: "/avatars/avatar-5.jpg",
    },
    car: {
      name: "Toyota Camry",
      image: "/cars/camry.jpg",
      plate: "LAG-620-SS",
    },
    startDate: "2025-12-23",
    endDate: "2025-12-30",
    amount: "₦182,000",
    status: "Ongoing",
  },
  {
    id: "ORD-7834",
    customer: {
      name: "Bruce Wayne",
      email: "bruce@wayne.com",
      image: "/avatars/avatar-7.jpg",
    },
    car: { name: "GMC Yukon", image: "/cars/yukon.jpg", plate: "LAG-613-LL" },
    startDate: "2025-12-15",
    endDate: "2025-12-18",
    amount: "₦180,000",
    status: "Completed",
  },
  {
    id: "ORD-7835",
    customer: {
      name: "Ellen Ripley",
      email: "ellen.r@example.com",
      image: "/avatars/avatar-6.jpg",
    },
    car: {
      name: "Ford Escape",
      image: "/cars/escape.jpg",
      plate: "LAG-203-CD",
    },
    startDate: "2025-12-24",
    endDate: "2025-12-26",
    amount: "₦42,000",
    status: "Pending",
  },
  {
    id: "ORD-7836",
    customer: {
      name: "Clark Kent",
      email: "clark.k@dailyplanet.com",
      image: "/avatars/avatar-2.jpg",
    },
    car: { name: "Lexus ES", image: "/cars/lexus_es.jpg", plate: "LAG-612-KK" },
    startDate: "2025-12-10",
    endDate: "2025-12-12",
    amount: "₦110,000",
    status: "Completed",
  },
  {
    id: "ORD-7837",
    customer: {
      name: "Diana Prince",
      email: "diana.p@themyscira.com",
      image: "/avatars/avatar-1.jpg",
    },
    car: {
      name: "Mercedes C-Class",
      image: "/cars/mercedes_c.jpg",
      plate: "LAG-604-CC",
    },
    startDate: "2025-12-25",
    endDate: "2026-01-05",
    amount: "₦572,000",
    status: "Approved",
  },
  {
    id: "ORD-7838",
    customer: {
      name: "Tony Stark",
      email: "tony@stark.com",
      image: "/avatars/avatar-3.jpg",
    },
    car: { name: "Audi A4", image: "/cars/audi_a4.jpg", plate: "LAG-605-DD" },
    startDate: "2025-11-01",
    endDate: "2025-11-05",
    amount: "₦240,000",
    status: "Completed",
  },
  {
    id: "ORD-7839",
    customer: {
      name: "Steve Rogers",
      email: "steve.r@avengers.com",
      image: "/avatars/avatar-4.jpg",
    },
    car: {
      name: "Subaru Outback",
      image: "/cars/outback.jpg",
      plate: "LAG-606-EE",
    },
    startDate: "2025-12-05",
    endDate: "2025-12-07",
    amount: "₦44,000",
    status: "Completed",
  },
  {
    id: "ORD-7840",
    customer: {
      name: "Natasha Romanoff",
      email: "natasha.r@shield.gov",
      image: "/avatars/avatar-5.jpg",
    },
    car: { name: "Mazda 6", image: "/cars/mazda6.jpg", plate: "LAG-611-JJ" },
    startDate: "2025-12-25",
    endDate: "2025-12-27",
    amount: "₦39,000",
    status: "Pending",
  },
  {
    id: "ORD-7841",
    customer: {
      name: "Peter Parker",
      email: "peter.p@midtown.edu",
      image: "/avatars/avatar-6.jpg",
    },
    car: { name: "Mini Cooper", image: "/cars/mini.jpg", plate: "LAG-619-RR" },
    startDate: "2025-12-20",
    endDate: "2025-12-20",
    amount: "₦25,000",
    status: "Ongoing",
  },
  {
    id: "ORD-7842",
    customer: {
      name: "Wanda Maximoff",
      email: "wanda.m@westview.com",
      image: "/avatars/avatar-7.jpg",
    },
    car: {
      name: "Peugeot 3008",
      image: "/cars/peugeot3008.jpg",
      plate: "LAG-616-OO",
    },
    startDate: "2025-12-18",
    endDate: "2025-12-22",
    amount: "₦72,000",
    status: "Completed",
  },
  {
    id: "ORD-7843",
    customer: {
      name: "Vision",
      email: "vision@android.com",
      image: "/avatars/avatar-1.jpg",
    },
    car: {
      name: "Volkswagen Passat",
      image: "/cars/passat.jpg",
      plate: "LAG-609-HH",
    },
    startDate: "2025-12-26",
    endDate: "2025-12-28",
    amount: "₦42,000",
    status: "Approved",
  },
];
